const myProject = [
  {
    id: 1,
    name: "Bazar Pro",
    title: "E-commerce Template",
    thumbnail: "",
    description:
      "Bazar Pro is an E-commerce Template that is sold on Material-UI official website",
    features: null,
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_link:
      "https://mui.com/store/previews/bazar-pro-react-ecommerce-template/",
  },
  {
    id: 2,
    name: "Trackem-GPS",
    title: "GPS Tracking Web App",
    thumbnail: "",
    description: "Trackem-GPS is a GPS Tracking App which is based on web",
    features: null,
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_link: "https://trackem.vercel.app/",
  },
  {
    id: 3,
    name: "Opacity Studio",
    title: "Portfolio Landing Page",
    thumbnail: "",
    description:
      "Opacity Studio is a landing page website. It's developed for a wonderful portfolio.",
    features: null,
    technologies: ["React", "NextJS", "Material-UI", "TypeScript"],
    live_link: "https://trackem.vercel.app/",
  },
  {
    id: 4,
    name: "GUll React",
    title: "Admin Dashboard Template",
    thumbnail: "",
    description: "GUll is an Admin Dashboard Template",
    features: null,
    technologies: ["React", "Material-UI", "TypeScript"],
    live_link: "https://gull-mui-typescript.vercel.app/",
  },
  {
    id: 5,
    name: "Matx React Pro",
    title: "Admin Dashboard Template",
    thumbnail: "",
    description: "Matx React Pro is an Admin Dashboard Template",
    features: null,
    technologies: ["React", "Material-UI"],
    live_link: "http://matx-react.ui-lib.com/",
  },
  {
    id: 6,
    name: "Matx React",
    title: "Admin Dashboard Template Free",
    thumbnail: "",
    description: "Matx React is a free version of Matx React Pro template",
    features: null,
    technologies: ["React", "Material-UI"],
    live_link: "https://matx-react-free.vercel.app/",
  },
  {
    id: 7,
    name: "My Blog (MERN)",
    title: "Multi-Author Blogging System",
    thumbnail:
      "https://res.cloudinary.com/dj7k9b8ps/image/upload/v1623130196/projectImage/nv7m6t3kggrepn5cqo1j.png",
    description: "This is a MERN Multi-Author Blogging web app",
    features: [
      "Multi-author blogging website.",
      "User can Read and create an article.",
      "User can filter and Search any articles.",
      "Any user can see popular authors and popular articles.",
      "User has to register for create an Author profile.",
      "Before Complete registration, the user email will be verify.",
      "The author can set and edit her profile.",
      "An author can bookmark of other authors’ articles.",
      "Author can create, edit and delete her created article.",
      "A registered user can like, dislike and comment on any article.",
      "Registered users can follow and unfollow other registered users.",
      "It has a dashboard for maintenance and monitoring author activities.",
    ],
    technologies: [
      "SASS",
      "Material UI",
      "ReactJS",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
    ],
    live_link: "https://my-blog-article.web.app/",
  },
  {
    id: 8,
    name: "Doctor's Garden (MERN)",
    title: "Hospital Web App",
    image:
      "https://res.cloudinary.com/dj7k9b8ps/image/upload/v1623229718/projectImage/ldqlliklfyzdmbkuzgl5.png",
    description: "A Single-page MERN Stack hospital web-app.",
    features: [
      "Separate Patient registration.",
      "Separate doctor registration.",
      "Online Appointment booking for patinet.",
      "Online appointment making for patients.",
      "Doctor will review the patient's appointments.",
      "Doctor Can approve or reject the patient.",
      "Doctor can see appointed the patient's list.",
      "Separate Doctor Dashboard.",
      "Separate Patient Dashboard to monitoring appointment status.",
      "Doctor can provide prescription for each patient online.",
    ],
    technologies: ["Material UI", "ReactJS", "NodeJS", "ExpressJS", "MongoDB"],
    live_link: "https://doctor-garden1.web.app/",
  },
  {
    id: 9,
    name: "Red Onion (MERN)",
    title: "Restaurant Website",
    image:
      "https://res.cloudinary.com/dj7k9b8ps/image/upload/v1606132011/projectImage/x7k77o8spqizx0iz6iwl.png",
    description: "A single page MERN Stack restaurant website.",
    features: [
      "Users can select any food in the cart.",
      "They can order food from the cart.",
      "Users have to sign up to place an order.",
      "Pay online using their credit card.",
      "After order, they can see the order details.",
      "Every logged-in user has a profile page.",
      "Logged in users can see their previous order history.",
    ],
    technologies: [
      "Material UI",
      "ReactJS",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Firebase",
    ],
    live_link: "https://red-onion-restaurant-25d46.web.app/",
  },
];
